### ISSUE TITLE
Document update procedure

### ISSUE THREAD

**Issue by 3nids** [opengisch/signalo#158]
drop app schema
run deltas
re-create app

**Comment by spch-GL** [comment]
Je vais tester la mise à jour sur notre base de test tout prochainement.
En attendant, comment savoir quels deltas appliquer sur la base en cours ? 

Ne serait-il pas judicieux d'ajouter une table indiquant quels deltas ont été passés, quand et par qui (comme dans OpenComptage) ?

**Comment by spch-GL** [comment]
Avec la version 1.0.0 RC6, il manque une documentation pour faire fonctionner `create_app.py` :

```
30.01.2024_18:20:38.76 C:\apps\_dev\SIRO\signalo-1.0.0-RC6>python datamodel\app\create_app.py
Traceback (most recent call last):
  File "C:\apps\_dev\SIRO\signalo-1.0.0-RC6\datamodel\app\create_app.py", line 50, in <module>
    create_views(args.srid, args.pg_service)
  File "C:\apps\_dev\SIRO\signalo-1.0.0-RC6\datamodel\app\create_app.py", line 32, in create_views
    run_sql("datamodel/app/drop_schema.sql", pg_service, variables)
  File "C:\apps\_dev\SIRO\signalo-1.0.0-RC6\datamodel\app\create_app.py", line 16, in run_sql
    conn = psycopg2.connect(f"service={pg_service}")
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: definition of service "None" not found


30.01.2024_18:20:38.96 C:\apps\_dev\SIRO\signalo-1.0.0-RC6>
```
